{
 "title": "SpeedTests",
 "description": "A dashboard to display speedtest data over time.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "SHOW TAG VALUES FROM ping WITH Key = \"namespace\""
   }
  ]
 },
 "panels": [
  { "title": "Připojení", "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 } },
  { "title": "Stav spojení", "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 } },
  {
   "title": "Avg Download Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Speedtest Results",
   "type": "timeseries",
   "description": "Uses https://github.com/breadlysm/speedtest-to-influxdb",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "download",
     "query": "SELECT mean(\"bytes\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "upload",
     "query": "SELECT mean(\"bytes\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Test Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Upload Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Test Downloaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Test Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Test Uploaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "pings",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "High Frequency Ping Results",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "pings",
     "query": "SELECT mean(\"bytes\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "pings",
     "query": "SELECT mean(\"round_trip_time_avg\") FROM \"pings\" WHERE (\"namespace\" =~ /^$namespace$/) AND success = 1 AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Ping Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pings",
     "query": "SELECT mean(\"round_trip_time_avg\") FROM \"pings\" WHERE (\"namespace\" =~ /^$namespace$/) AND success = 1 AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Rount Trip Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_target",
     "groupBy": [
      { "params": [ "target::tag" ], "type": "tag" }
     ],
     "measurement": "pings",
     "select": [
      [
       { "params": [ "round_trip_time_avg" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leaders (Green) & Laggers (Yellow)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Averages by Test Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "description": "Shows the avg speeds received by test site",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "server_name" ], "type": "tag" },
        { "params": [ "server_location" ], "type": "tag" },
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT mean(\"bandwidth\") AS \"Download Avg\" FROM \"download\" WHERE $timeFilter GROUP BY \"server_name\", \"server_location\"",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Download Avg" ], "type": "alias" }
        ],
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Test Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "upload",
       "query": "SELECT mean(\"bandwidth\") AS \"Upload Avg\" FROM \"upload\" WHERE $timeFilter GROUP BY \"server_id\"",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Upload Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "ping",
       "query": "SELECT mean(\"bandwidth\") AS \"Upload Avg\" FROM \"upload\" WHERE $timeFilter GROUP BY \"server_id\"",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Ping" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Results & Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Raw",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}